baseURL = 'https://webikor.ru/'
languageCode = 'ru-RU'
title = 'Webikor'
theme = 'ananke'

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number


[[menu.main]]
	name = 'О сайте'
	url = '/about/'
	weight = 1


[services.disqus]
  shortname = 'webikor'

[params]
  commentoEnable = false
	text_color = ""
	author = ""
	favicon = "/images/favicon.ico"
	site_logo = ""
	description = "The last theme you'll ever need. Maybe."
